spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timecard-app?autoReconnect=true&useSSL=false&serverTimezone=JST
    username: root
    password: Komeumai12
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: jdbc
